import Foundation

let welshStrings: [String: String] = [
    // Language Selection
    "language.chooseTitle": "Dewiswch Eich Iaith",
    "language.english": "English",
    "language.welsh": "Cymraeg",
    "language.tapToSelect": "Tapiwch faner i ddewis eich iaith",

    // Main Menu
    "menu.title1": "GemMine",
    "menu.title2": "QUEST",
    "menu.tagline": "Cloddiwch am emau gwerthfawr yn ddwfn dan ddaear",
    "menu.startMining": "DECHRAU CLODDIO",
    "menu.continueMining": "PARHAU I GLODDIO",
    "menu.shop": "Siop",
    "menu.settings": "Gosodiadau",
    "menu.level": "LEFEL",
    "menu.stars": "S\u{00CA}R",
    "menu.totalScore": "SGÔR LLAWN",
    "menu.exit": "Gadael",

    // Level Map
    "levelMap.title": "Siafft y Mwynglawdd",
    "levelMap.free": "AM DDIM",
    "levelMap.levelLocked": "Lefel Ar Glo",
    "levelMap.ok": "Iawn",
    "levelMap.lockedMessage": "Cwblhewch y lefelau blaenorol yn gyntaf i gloddio'n ddyfnach i'r siafft!",

    // Level Detail
    "levelDetail.level": "Lefel %d",
    "levelDetail.superHard": "Anodd Iawn",
    "levelDetail.hard": "Anodd",
    "levelDetail.best": "Gorau: %d",
    "levelDetail.objectives": "Amcanion",
    "levelDetail.moves": "%d symudiad",
    "levelDetail.shuffleWarning": "Mae gemau'n cymysgu bob 3 symudiad!",
    "levelDetail.digAgain": "CLODDIO ETO",
    "levelDetail.startDig": "DECHRAU CLODDIO",

    // Game Container
    "game.lv": "Lf.%d",
    "game.moves": "Symudiadau",
    "game.movesTooltip": "Symudiadau ar ôl. Cyfatebwch emau'n ddoeth cyn iddynt redeg allan!",
    "game.scoresTooltip": "Eich sgôr presennol ar gyfer y lefel hon. Enillwch bwyntiau drwy gyfateb gemau ac actifadu arbenigeddau.",
    "game.shopTooltip": "Agorwch y siop i brynu hwbiau gyda darnau arian.",
    "game.god": "DUW",
    "game.godModeOn": "Symudiadau diderfyn YMLAEN",
    "game.godModeOff": "Symudiadau diderfyn I FFWRDD",
    "game.freeBooster": "Hwb %@ am ddim! (gwobr 10 ymgais)",
    "game.retryLevel": "Ail-geisio — Lefel %d",
    "game.levelName": "Lefel %d — %@",
    "game.leaveGame": "Gadael y Gêm?",
    "game.continuePlaying": "Parhau i Chwarae",
    "game.leave": "Gadael",
    "game.progressLost": "Bydd cynnydd ar y lefel hon yn cael ei golli.",
    "game.getReady": "Paratowch i gloddio...",

    // Game Over
    "gameOver.levelComplete": "Lefel %d Wedi'i Chwblhau!",
    "gameOver.shaftCollapsed": "Siafft Wedi Cwympo!",
    "gameOver.outOfMoves": "Dim symudiadau ar ôl",
    "gameOver.points": "%d pwynt",
    "gameOver.goldReward": "+%d aur",
    "gameOver.nextLevel": "Lefel Nesaf",
    "gameOver.retry": "Ail-geisio",
    "gameOver.backToMap": "Nôl i'r Map",
    "gameOver.needMoreMoves": "Angen mwy o symudiadau?",
    "gameOver.goldAvailable": "%d aur ar gael",
    "gameOver.plusMove": "+%d symudiad",
    "gameOver.plusMoves": "+%d symudiad",

    // Settings
    "settings.title": "Gosodiadau",
    "settings.godMode": "Modd Duw",
    "settings.godModeDesc": "Symudiadau diderfyn - ar gyfer chwarae hamddenol",
    "settings.gameplay": "Chwarae",
    "settings.hapticFeedback": "Adborth Haptig",
    "settings.feedback": "Adborth",
    "settings.boosters": "Hwbiau",
    "settings.boosterNote": "+1 o bob un bob 25 lefel",
    "settings.highestLevel": "Lefel Uchaf",
    "settings.levelsCompleted": "Lefelau Cwblhawyd",
    "settings.totalStars": "Cyfanswm Sêr",
    "settings.progress": "Cynnydd",
    "settings.resetAllProgress": "Ailosod Pob Cynnydd",
    "settings.resetProgress": "Ailosod Cynnydd?",
    "settings.cancel": "Canslo",
    "settings.reset": "Ailosod",
    "settings.resetMessage": "Bydd hyn yn dileu eich holl gynnydd lefel a sgoriau. Ni ellir dadwneud hyn.",
    "settings.max5": "Uchaf: 5",
    "settings.language": "Iaith",

    // Shop
    "shop.title": "SIOP Y MWYNGLAWDD",
    "shop.owned": "Perchennog: %d",

    // Daily Reward
    "daily.title": "BONWS CLODDIO DYDDIOL",
    "daily.dayStreak": "Diwrnod %d/7",
    "daily.day": "Diwrnod %d",
    "daily.claimed": "Hawliwyd!",
    "daily.claim": "HAWLIO",
    "daily.continue": "Parhau",
    "daily.skip": "Hepgor",

    // Spin Wheel
    "spin.title": "TROELL LWCUS Y MWYNGLAWDD",
    "spin.youWon": "RYDYCH WEDI ENNILL!",
    "spin.collect": "CASGLU",
    "spin.spin": "TROELLI!",
    "spin.close": "Cau",
    "spin.gold100": "100 Aur",
    "spin.gold500": "500 Aur",
    "spin.pickaxe": "Caib",
    "spin.dynamite": "Dynameit",
    "spin.gems2": "2 Em",
    "spin.drone": "Drôn",
    "spin.gemForge": "Gefail Emau",

    // Boosters
    "booster.pickaxe": "Caib",
    "booster.dynamite": "Dynameit",
    "booster.gemForge": "Gefail Emau",
    "booster.droneStrike": "Streic Drôn",
    "booster.mineCartRush": "Rhuthr Cert Mwynglawdd",
    "booster.pickaxeShort": "Caib",
    "booster.dynamiteShort": "Dynameit",
    "booster.forgeShort": "Gefail",
    "booster.droneShort": "Drôn",
    "booster.cartShort": "Cert",
    "booster.pickaxeHintShort": "Torri 1",
    "booster.dynamiteHintShort": "Ffrwydro 3x3",
    "booster.forgeHintShort": "Gosod arbenigol",
    "booster.droneHintShort": "Chwilio 5",
    "booster.cartHintShort": "Clirio rhes",
    "booster.pickaxeHint": "Caib — Tapiwch unrhyw em i'w dinistrio ar unwaith",
    "booster.dynamiteHint": "Dynameit — Tapiwch i ffrwydro ardal 3x3",
    "booster.gemForgeHint": "Gefail Emau — Yn gosod Pêl Grisial ac em Ansefydlog",
    "booster.droneStrikeHint": "Streic Drôn — 5 chwiliwyr yn targedu emau ar hap",
    "booster.mineCartRushHint": "Rhuthr Cert — Yn troi rhes yn emau laser",

    // Achievement
    "achievement.unlocked": "Cyflawniad Wedi'i Ddatgloi!",
    "achievement.gold": "+%d Aur",
    "achievement.firstDig": "Cloddiad Cyntaf",
    "achievement.apprenticeMiner": "Mwynwr Prentis",
    "achievement.journeymanMiner": "Mwynwr Siwrne",
    "achievement.masterMiner": "Meistr Mwynwr",
    "achievement.legendaryMiner": "Mwynwr Chwedlonol",
    "achievement.starCollector": "Casglwr Sêr",
    "achievement.starHoarder": "Pentyrwr Sêr",
    "achievement.perfectRun": "Rhediad Perffaith",
    "achievement.comboKing": "Brenin Combo",
    "achievement.explosionExpert": "Arbenigwr Ffrwydro",
    "achievement.gemHunter": "Heliwr Emau",
    "achievement.dailyDevotion": "Ymroddiad Dyddiol",
    "achievement.fortuneSeeker": "Ceisiwr Ffortiwn",
    "achievement.firstDigDesc": "Cwblhewch eich lefel gyntaf",
    "achievement.apprenticeMinerDesc": "Cwblhewch 10 lefel",
    "achievement.journeymanMinerDesc": "Cwblhewch 25 lefel",
    "achievement.masterMinerDesc": "Cwblhewch 50 lefel",
    "achievement.legendaryMinerDesc": "Cwblhewch 100 lefel",
    "achievement.starCollectorDesc": "Enillwch 50 seren i gyd",
    "achievement.starHoarderDesc": "Enillwch 200 seren i gyd",
    "achievement.perfectRunDesc": "Enillwch 3 seren ar unrhyw lefel",
    "achievement.comboKingDesc": "Cwblhewch 5 lefel yn olynol",
    "achievement.explosionExpertDesc": "Defnyddiwch 10 hwb dynameit",
    "achievement.gemHunterDesc": "Casglwch 500 em i gyd",
    "achievement.dailyDevotionDesc": "Hawliwch 7 gwobr ddyddiol yn olynol",
    "achievement.fortuneSeekerDesc": "Troellwch yr olwyn 10 gwaith",

    // Event Banner
    "event.weekendRush": "Rhuthr Cloddio'r Penwythnos",
    "event.doubleGold": "Aur dwbl ar bob lefel!",
    "event.start": "Dechrau",

    // Milestone
    "milestone.reached": "CARREG FILLTIR!",
    "milestone.starsEarned": "%@ Seren Wedi'u Hennill!",
    "milestone.levelsCompleted": "%@ Lefel Wedi'u Cwblhau!",
    "milestone.reward": "+200 Aur a 3 em",
    "milestone.awesome": "GWYCH!",

    // Objectives
    "objective.reachScore": "Sgorio %d pwynt",
    "objective.clearAllOre": "Cloddio pob teilsen mwyn",
    "objective.dropTreasures": "Gollwng %d trysor(au) i'r cert mwynglawdd",
    "objective.dropTreasure1": "Gollwng %d trysor i'r cert mwynglawdd",
    "objective.collectGems": "Casglu %d %@(au) (%@)",
    "objective.collectGem1": "Casglu %d %@ (%@)",
    "objective.collectSpecials": "Creu %d %@(au)",
    "objective.collectSpecial1": "Creu %d %@",
    "objective.reachScoreDesc": "Sgoriwch o leiaf %d pwynt drwy gyfateb gemau",
    "objective.clearAllOreDesc": "Cyfatebwch emau ar deilsiau mwyn aur i'w cloddio. Nid yw hwbiau'n cyfrif!",
    "objective.dropTreasuresDesc": "Symudwch %d trysor(au) i'r cert mwynglawdd ar y gwaelod",
    "objective.dropTreasure1Desc": "Symudwch %d trysor i'r cert mwynglawdd ar y gwaelod",
    "objective.collectGemsDesc": "Cyfatebwch a chasglwch %d em %@ (%@)",
    "objective.collectSpecialsDesc": "Crëwch %d em %@(au) drwy gyfatebiadau arbennig",
    "objective.collectSpecial1Desc": "Crëwch %d em %@ drwy gyfatebiad arbennig",
    "objective.reachScoreShort": "%d pnt",
    "objective.clearAllOreShort": "Clirio mwyn",
    "objective.clearAllOreShortColor": "Clirio pob mwyn",
    "objective.dropTreasuresShort": "%d trysor(au)",
    "objective.dropTreasure1Short": "%d trysor",

    // Gem Types
    "gem.ruby": "Rhuddem",
    "gem.gold": "Aur",
    "gem.silver": "Arian",
    "gem.emerald": "Emrallt",
    "gem.sapphire": "Saffir",
    "gem.amethyst": "Amethyst",
    "gem.hintRed": "coch",
    "gem.hintGold": "aur",
    "gem.hintSilver": "arian",
    "gem.hintGreen": "gwyrdd",
    "gem.hintBlue": "glas",
    "gem.hintPurple": "porffor",

    // Special Types
    "special.normal": "Normal",
    "special.laserH": "Em Laser (Ll)",
    "special.laserV": "Em Laser (F)",
    "special.volatile": "Em Ansefydlog",
    "special.crystalBall": "Pêl Grisial",
    "special.miningDrone": "Drôn Mwyngloddio",

    // Shop Items
    "shopItem.pickaxe3": "Caib x3",
    "shopItem.pickaxe10": "Caib x10",
    "shopItem.dynamite1": "Dynameit",
    "shopItem.dynamite5": "Dynameit x5",
    "shopItem.drone1": "Streic Drôn",
    "shopItem.drone3": "Drôn x3",
    "shopItem.forge1": "Gefail Emau",
    "shopItem.forge3": "Gefail x3",
    "shopItem.cart1": "Cert Mwynglawdd",
]
