import Foundation

let englishStrings: [String: String] = [
    // Language Selection
    "language.chooseTitle": "Choose Your Language",
    "language.english": "English",
    "language.welsh": "Cymraeg",
    "language.tapToSelect": "Tap a flag to select your language",

    // Main Menu
    "menu.title1": "GemMine",
    "menu.title2": "QUEST",
    "menu.tagline": "Mine precious gems deep underground",
    "menu.startMining": "START MINING",
    "menu.continueMining": "CONTINUE MINING",
    "menu.shop": "Shop",
    "menu.settings": "Settings",
    "menu.level": "LEVEL",
    "menu.stars": "STARS",
    "menu.totalScore": "TOTAL SCORE",
    "menu.exit": "Exit",

    // Level Map
    "levelMap.title": "Mine Shaft",
    "levelMap.free": "FREE",
    "levelMap.levelLocked": "Level Locked",
    "levelMap.ok": "OK",
    "levelMap.lockedMessage": "Complete the previous levels first to dig deeper into the mine shaft!",

    // Level Detail
    "levelDetail.level": "Level %d",
    "levelDetail.superHard": "Super Hard",
    "levelDetail.hard": "Hard",
    "levelDetail.best": "Best: %d",
    "levelDetail.objectives": "Objectives",
    "levelDetail.moves": "%d moves",
    "levelDetail.shuffleWarning": "Gems shuffle every 3 moves!",
    "levelDetail.digAgain": "DIG AGAIN",
    "levelDetail.startDig": "START DIG",

    // Game Container
    "game.lv": "Lv.%d",
    "game.moves": "Moves",
    "game.movesTooltip": "Moves remaining. Match gems wisely before they run out!",
    "game.scoresTooltip": "Your current score for this level. Earn points by matching gems and activating specials.",
    "game.shopTooltip": "Open the shop to buy boosters with coins.",
    "game.god": "GOD",
    "game.godModeOn": "Unlimited moves ON",
    "game.godModeOff": "Unlimited moves OFF",
    "game.freeBooster": "Free %@ booster! (10 attempts reward)",
    "game.retryLevel": "Retry — Level %d",
    "game.levelName": "Level %d — %@",
    "game.leaveGame": "Leave Game?",
    "game.continuePlaying": "Continue Playing",
    "game.leave": "Leave",
    "game.progressLost": "Progress on this level will be lost.",
    "game.getReady": "Get ready to dig...",

    // Game Over
    "gameOver.levelComplete": "Level %d Complete!",
    "gameOver.shaftCollapsed": "Shaft Collapsed!",
    "gameOver.outOfMoves": "Out of moves",
    "gameOver.points": "%d points",
    "gameOver.goldReward": "+%d gold",
    "gameOver.nextLevel": "Next Level",
    "gameOver.retry": "Retry",
    "gameOver.backToMap": "Back to Map",
    "gameOver.needMoreMoves": "Need more moves?",
    "gameOver.goldAvailable": "%d gold available",
    "gameOver.plusMove": "+%d move",
    "gameOver.plusMoves": "+%d moves",

    // Settings
    "settings.title": "Settings",
    "settings.godMode": "God Mode",
    "settings.godModeDesc": "Unlimited moves - for casual play",
    "settings.gameplay": "Gameplay",
    "settings.hapticFeedback": "Haptic Feedback",
    "settings.feedback": "Feedback",
    "settings.boosters": "Boosters",
    "settings.boosterNote": "+1 of each every 25 levels",
    "settings.highestLevel": "Highest Level",
    "settings.levelsCompleted": "Levels Completed",
    "settings.totalStars": "Total Stars",
    "settings.progress": "Progress",
    "settings.resetAllProgress": "Reset All Progress",
    "settings.resetProgress": "Reset Progress?",
    "settings.cancel": "Cancel",
    "settings.reset": "Reset",
    "settings.resetMessage": "This will erase all your level progress and scores. This cannot be undone.",
    "settings.max5": "Max: 5",
    "settings.language": "Language",

    // Shop
    "shop.title": "MINE SHOP",
    "shop.owned": "Owned: %d",

    // Daily Reward
    "daily.title": "DAILY MINING BONUS",
    "daily.dayStreak": "Day %d/7",
    "daily.day": "Day %d",
    "daily.claimed": "Claimed!",
    "daily.claim": "CLAIM",
    "daily.continue": "Continue",
    "daily.skip": "Skip",

    // Spin Wheel
    "spin.title": "LUCKY MINE SPIN",
    "spin.youWon": "YOU WON!",
    "spin.collect": "COLLECT",
    "spin.spin": "SPIN!",
    "spin.close": "Close",
    "spin.gold100": "100 Gold",
    "spin.gold500": "500 Gold",
    "spin.pickaxe": "Pickaxe",
    "spin.dynamite": "Dynamite",
    "spin.gems2": "2 Gems",
    "spin.drone": "Drone",
    "spin.gemForge": "Gem Forge",

    // Boosters
    "booster.pickaxe": "Pickaxe",
    "booster.dynamite": "Dynamite",
    "booster.gemForge": "Gem Forge",
    "booster.droneStrike": "Drone Strike",
    "booster.mineCartRush": "Mine Cart Rush",
    "booster.pickaxeShort": "Pickaxe",
    "booster.dynamiteShort": "Dynamite",
    "booster.forgeShort": "Forge",
    "booster.droneShort": "Drone",
    "booster.cartShort": "Cart",
    "booster.pickaxeHintShort": "Break 1",
    "booster.dynamiteHintShort": "Blast 3x3",
    "booster.forgeHintShort": "Place specials",
    "booster.droneHintShort": "Seek 5",
    "booster.cartHintShort": "Row clear",
    "booster.pickaxeHint": "Pickaxe — Tap any gem to destroy it instantly",
    "booster.dynamiteHint": "Dynamite — Tap to blast a 3x3 area",
    "booster.gemForgeHint": "Gem Forge — Places a Crystal Ball and Volatile gem",
    "booster.droneStrikeHint": "Drone Strike — 5 seekers target random gems",
    "booster.mineCartRushHint": "Mine Cart Rush — Converts a row to laser gems",

    // Achievement
    "achievement.unlocked": "Achievement Unlocked!",
    "achievement.gold": "+%d Gold",
    "achievement.firstDig": "First Dig",
    "achievement.apprenticeMiner": "Apprentice Miner",
    "achievement.journeymanMiner": "Journeyman Miner",
    "achievement.masterMiner": "Master Miner",
    "achievement.legendaryMiner": "Legendary Miner",
    "achievement.starCollector": "Star Collector",
    "achievement.starHoarder": "Star Hoarder",
    "achievement.perfectRun": "Perfect Run",
    "achievement.comboKing": "Combo King",
    "achievement.explosionExpert": "Explosion Expert",
    "achievement.gemHunter": "Gem Hunter",
    "achievement.dailyDevotion": "Daily Devotion",
    "achievement.fortuneSeeker": "Fortune Seeker",
    "achievement.firstDigDesc": "Complete your first level",
    "achievement.apprenticeMinerDesc": "Complete 10 levels",
    "achievement.journeymanMinerDesc": "Complete 25 levels",
    "achievement.masterMinerDesc": "Complete 50 levels",
    "achievement.legendaryMinerDesc": "Complete 100 levels",
    "achievement.starCollectorDesc": "Earn 50 total stars",
    "achievement.starHoarderDesc": "Earn 200 total stars",
    "achievement.perfectRunDesc": "Earn 3 stars on any level",
    "achievement.comboKingDesc": "Complete 5 levels in a row",
    "achievement.explosionExpertDesc": "Use 10 dynamite boosters",
    "achievement.gemHunterDesc": "Collect 500 gems total",
    "achievement.dailyDevotionDesc": "Claim 7 daily rewards in a row",
    "achievement.fortuneSeekerDesc": "Spin the wheel 10 times",

    // Event Banner
    "event.weekendRush": "Weekend Mining Rush",
    "event.doubleGold": "Double Gold on all levels!",
    "event.start": "Start",

    // Milestone
    "milestone.reached": "MILESTONE REACHED!",
    "milestone.starsEarned": "%@ Stars Earned!",
    "milestone.levelsCompleted": "%@ Levels Completed!",
    "milestone.reward": "+200 Gold & 3 gems",
    "milestone.awesome": "AWESOME!",

    // Objectives
    "objective.reachScore": "Score %d points",
    "objective.clearAllOre": "Mine all ore tiles",
    "objective.dropTreasures": "Drop %d treasure(s) to mine cart",
    "objective.dropTreasure1": "Drop %d treasure to mine cart",
    "objective.collectGems": "Collect %d %@(s) (%@)",
    "objective.collectGem1": "Collect %d %@ (%@)",
    "objective.collectSpecials": "Create %d %@(s)",
    "objective.collectSpecial1": "Create %d %@",
    "objective.reachScoreDesc": "Score at least %d points by matching gems",
    "objective.clearAllOreDesc": "Match gems on gold ore tiles to mine them. Boosters don't count!",
    "objective.dropTreasuresDesc": "Move %d treasure(s) to the mine cart at the bottom",
    "objective.dropTreasure1Desc": "Move %d treasure to the mine cart at the bottom",
    "objective.collectGemsDesc": "Match and collect %d %@ gems (%@)",
    "objective.collectSpecialsDesc": "Create %d %@ gem(s) through special matches",
    "objective.collectSpecial1Desc": "Create %d %@ gem through special matches",
    "objective.reachScoreShort": "%d pts",
    "objective.clearAllOreShort": "Clear ore",
    "objective.clearAllOreShortColor": "Clear all ore",
    "objective.dropTreasuresShort": "%d treasure(s)",
    "objective.dropTreasure1Short": "%d treasure",

    // Gem Types
    "gem.ruby": "Ruby",
    "gem.gold": "Gold",
    "gem.silver": "Silver",
    "gem.emerald": "Emerald",
    "gem.sapphire": "Sapphire",
    "gem.amethyst": "Amethyst",
    "gem.hintRed": "red",
    "gem.hintGold": "gold",
    "gem.hintSilver": "silver",
    "gem.hintGreen": "green",
    "gem.hintBlue": "blue",
    "gem.hintPurple": "purple",

    // Special Types
    "special.normal": "Normal",
    "special.laserH": "Laser Gem (H)",
    "special.laserV": "Laser Gem (V)",
    "special.volatile": "Volatile Gem",
    "special.crystalBall": "Crystal Ball",
    "special.miningDrone": "Mining Drone",

    // Shop Items
    "shopItem.pickaxe3": "Pickaxe x3",
    "shopItem.pickaxe10": "Pickaxe x10",
    "shopItem.dynamite1": "Dynamite",
    "shopItem.dynamite5": "Dynamite x5",
    "shopItem.drone1": "Drone Strike",
    "shopItem.drone3": "Drone x3",
    "shopItem.forge1": "Gem Forge",
    "shopItem.forge3": "Forge x3",
    "shopItem.cart1": "Mine Cart",
]
