# Build and test GemMineQuest iOS project using Swift Package Manager

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild build -scheme GemMineQuest -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' | xcpretty || true
    - name: Run tests
      run: xcodebuild test -scheme GemMineQuestTests -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' | xcpretty
